Fixup after switch to CMake AUTOMOC
Header files must not leak the dependencies to their generated ui_xxx.h
counterparts. Thus always use pointer-based members for classes
generated by uic.

Fixes this and follow-up issues:
```
client/src/app/mainwindow.h:27:27: fatal error: ui_mainwindow.h: No such file or directory
```